# Introduction to numpy arrays

What is an array? You can think of arrays as a grid with values of the same type. Arrays can be multi-dimensional. 

### 1D Arrays

This is an example of a one dimensional (1D) array:

![1D array](1D_array.gif)


The 1D array has 1 row and 4 columns (remember Python begins indexing from 0) so it is a **1 x 10** array. Let's create the array above using numpy.

In [13]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# Array's dimensions
print("Number of dimensions: ", a.ndim)

# Number of elements in array
print("Elements in array: ", a.size)

# Number of rows and columns
print("(no. of columns): ", a.shape)

Number of dimensions:  1
Elements in array:  10
(no. of columns):  (10,)


In [19]:
# Find 5 in the array

a[4] # a[index]

5

What if we want more than one element from the array? Then, we specify a range. 

If we want the first five elements, our range is 0:5:1 which means all elements from index **0** to index **4** (notice that the value of the 5th index is not included) in steps of 1.


In [ ]:
a[0:5:1] #first five elements of the array

What about the last five elements?

What about all the even numbers?

#### Quick shortcuts with ranges:
The default start index is 0 and default end index is the last element in the array so if you don't specify an index, Python will takes these to be the default values. 
* a[ : ] - all elements. 
* a[ :5 ] - first five elements

### 2D Arrays

Let's make 'a' a two dimensional array with 2 rows and 5 columns i.e a **2 x 5** array. We use the function np.reshape(**number of rows**,**number of columns**)

So now the array looks like this:

| |0|1|2|3|4|
|-|-|-|-|-|-|
|**0**|1|2|3|4|x|
|**1**|6|7|8|9|10|

**5** is now in the 1st row and 5th column.

In [16]:
b = a.reshape(2,5)
print(b)
b[0,4] #b[row index, column index]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


5

What if we want the entire first row? 

In [17]:
print(b[0,0:5:1]) 
# or equivalently
print(b[0,:])

[1 2 3 4 5]
[1 2 3 4 5]


What about the first and second column?

### 3D Arrays

Now, we'll remove the last two elements in the 1D array and make it three dimensional! So now it looks more like this:

||0|1|
|-|-|-|
|**0**|1|2|
|**1**|3|4|

||0|1|
|-|-|-|
|**0**|x|6|
|**1**|7|8|

**5** is now in the 1st row and 1st column of the 2nd grid (i.e the third dimension)

In [18]:
c = a[0:8].reshape(2,2,2)
print(c)
c[1,0,0] #c[grid index, row index, column index]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


5

### Recap

![Multidimensional arrays](2D_3D_arrays.gif)

The arrays above are given to you. Find the values in the red boxes. 

In [ ]:
#1D:
a1 = np.arange(0,5,1) #for example
print(a1)

#insert value in red box

In [ ]:
#2D:
a2 = np.arange(0,15,1).reshape(3,5)
print(a2)

#insert value in red box

In [ ]:
#3D:
a3 = np.arange(0,45,1).reshape(3,3,5)
print(a3)

#insert value in red box

### Array operations

Use a for loop to multiply every element in the given array with 2 and print out the result. 

In [ ]:
array = np.arange(1,11,1)
print(array)

#for loop

You could do the same thing by typing in:

In [ ]:
print("1D:\n",array * 2)

# Works for multi-dimensional arrays too!
array2 = array.reshape(2,5)
print("2D:\n", array2*2)

In [ ]:
# Similarly, you can also do

print(array)

#Addition
print("Addition:\n", array + array)

#Subtraction
print("Subtraction:\n",array - array)

#Division
print("Division:\n",array/2)

#Remainder or modulus
print("Modulus:\n",array%2)

#Power
print("Power:\n",array**2)

### Challenge

Import the satellite data of sea surface temperture we worked with last class. Just use the data along the equator i.e the 2160th element
1. Convert all the entries from Celsius to Fahrenheit using F = 9/5 C + 32
1. Find the average temperature 
    * *Hint:* Check out the documentation for numpy's mean function (http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/generated/numpy.mean.html)
1. Subtract each temperature with the average temperature. You've just calculated sea surface temperature anomalies!
1. Plot out your results using matplotlib.

Insert pseudocode here:
```
pseudocode
```