### 1D

In [3]:
import numpy as np

A = np.array([1,2,3,4,5,6,7,8])
print(A)
print('Shape:',A.shape)

[1 2 3 4 5 6 7 8]
Shape: (8,)


Find mean of all elements in A.

### 2D

In [4]:
#2D

B = np.array([[1,2,3,4],[5,6,7,8]])
print(B)
print('Shape:',B.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)


Find mean of all elements in B. 

Find mean of B along its first dimension (i.e rows) and print its shape.

Find mean of B along its second dimension (i.e columns) and print its shape.

### 3D

In [5]:
C = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(C)
print('Shape:',C.shape)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
Shape: (3, 2, 4)


Find mean of all elements in C

Find mean of C along its first dimension (i.e number of grids) and print its shape.

### 4D

In [6]:
D = np.array([[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]],[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]])
print(D)
print('Shape:',D.shape)

[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]


 [[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]]
Shape: (2, 3, 2, 4)


Find mean of all elements in D.

Find mean of D along its first dimension and print its shape.